### ISSUE TITLE
Last step icon truncated

### ISSUE THREAD

**Issue by SeboRax** [fython/MaterialStepperView#12]
When view is not matching parent, last step icon is truncated

![image](https://user-images.githubusercontent.com/32392637/31018795-97d27c94-a52d-11e7-996c-0e3d34476f46.png)

**Comment by SeboRax** [comment]
Using following xml (root is a LinearLayout containing appbar and this) :

    <moe.feng.common.stepperview.VerticalStepperView
        android:id="@+id/verticalStepperView"
        android:layout_width="match_parent"
        app:step_line_color="@color/grey_400"
        app:step_normal_color="@color/grey_500"
        app:step_activated_color="@color/colorPrimary"
        app:step_error_highlight_color="@color/red_500"
        android:layout_height="0dp"
        android:layout_weight="1" />

![image](https://user-images.githubusercontent.com/32392637/31019052-be807764-a52e-11e7-8634-a3082cb8b07b.png)

**Comment by fython** [comment]
Thanks for feedback. I found this bug too. These days I will try to fix it.

**Comment by fython** [comment]
I'm sorry for finishing fix so late. Now it works well in commit 9128947afde0d5bb2ad62188634aaad9793e4603 . I will release new version of library soon.
