### ISSUE TITLE
Failed to resolve: moe.feng:MaterialStepperView:latest-version

### ISSUE THREAD

**Issue by agostini95** [fython/MaterialStepperView#14]
I've configured the gradle  as in description, by the way I have this message
Error:(30, 13) Failed to resolve: moe.feng:MaterialStepperView:latest-version
How it is possible?

**Comment by fython** [comment]
`latest-version` is a placeholder. Please replace it with a actual version code such as `0.2.3`.

**Comment by agostini95** [comment]
sorry 
too many hours in front of the pc, Thanks
