### ISSUE TITLE
Title and Stepper truncated with adapter

### ISSUE THREAD

**Issue by agostini95** [fython/MaterialStepperView#15]
Hi! I'am using the isStepperAdapter interface but i have this bad situation...title and last stepper icon are truncated: how it is possible?
![photo_2017-12-29_04-57-18](https://user-images.githubusercontent.com/15164274/34429178-d5c225f4-ec54-11e7-96bd-6db3c8593140.jpg)

**Comment by fython** [comment]
It's actually a bug. But I am sorry that I have no enough time to fix it now. Maybe I will solve these problems in a month.

A temporary solution is to set a summary for the last item to prevent icon from being clipped. (But I had no idea about the temporary solution that the title is truncated.)

**Comment by fython** [comment]
I'm sorry for finishing fix so late. Now it works well in commit 9128947afde0d5bb2ad62188634aaad9793e4603 . I will release new version of library soon.

**Comment by agostini95** [comment]
Dear Gwo Fung,
Thank you so much! I want to thank you because I use it in a simple prototype application for my university and it works fine! 
Andrea Agostini

Inviato da Posta per Windows 10

Da: Gwo Fung
Inviato: sabato 3 marzo 2018 00:28
A: fython/MaterialStepperView
Cc: agostini95; Author
Oggetto: Re: [fython/MaterialStepperView] Title and Stepper truncated withadapter (#15)

I'm sorry for finishing fix so late. Now it works well in commit 9128947 . I will release new version of library soon.
