### ISSUE TITLE
0.2.4 import issue

### ISSUE THREAD

**Issue by nuhkoca** [fython/MaterialStepperView#17]
Hey!

Thanks for the lib! I am trying to import the latest version but Gradle gives an error which is about > Could not resolve 0.2.4 >, please help thanks! Btw as it seems you don't support DataBinding in your onCreateCustomView method, right?

**Comment by pedro-jorge-pereira** [comment]
Hi,

Same problem here "Error:Failed to resolve: moe.feng:MaterialStepperView:0.2.4".

Thanks for the lib, it is very helpful.

PjP

**Comment by pedro-jorge-pereira** [comment]
Please check the pull request #18 

PjP

**Comment by fython** [comment]
@pedro-jorge-pereira Thank you very much. I will try to build `0.2.4.1`

**Comment by fython** [comment]
Now we can get latest version `moe.feng:MaterialStepperView:0.2.4.2` in jitpack.io. Thanks @pedro-jorge-pereira

**Comment by satyanpyla** [comment]
Thanks for your library, 
is there is any way to change the font for STEP-TITLE.  Thank You
