### ISSUE TITLE
Set different summary when step state is changed

### ISSUE THREAD

**Issue by tenSunFree** [fython/MaterialStepperView#7]
app:step_summary="", 是針對處理完之後 折疊起來的View, 顯示的摘要
那 有沒有考慮新增一個, 是針對尚未處理 但是摺疊起來的View, 顯示的摘要?

尚未處理 但是摺疊起來的View
![01](https://user-images.githubusercontent.com/23090085/29324146-b35e185a-8215-11e7-946e-3a545d46836f.jpg)

處理完之後 折疊起來的View
![02](https://user-images.githubusercontent.com/23090085/29324147-b600619e-8215-11e7-9001-b4c2dc5c9506.jpg)

**Comment by fython** [comment]
我感覺左側的圖示已經足夠清晰地向使用者顯示完成狀態，摘要用於描述步驟的內容就夠了。

其他人可能也會有相同的想法，我在下一個版本還是加一個已完成摘要文本的屬性吧（屆時命名為
 `app:step_summary_done`，可選參數，當為空值時無論是否已完成還是會使用 `app:step_summary`），供大家自行選擇需不需要使用。

**Comment by fython** [comment]
New attribute is added in commit e1e32816d0e18e2409e717a3dcbeb11e27daf524 . 

------

新參數已經在 e1e32816d0e18e2409e717a3dcbeb11e27daf524 提交中添加。
