### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by tenSunFree** [fython/MaterialStepperView#8]
請教一下

我為了要實現VerticalStepperItemView
![01](https://user-images.githubusercontent.com/23090085/29396205-07e47b92-8349-11e7-8773-16b4c1297597.jpg)

所以添加了VerticalStepperItemView的依賴
![03](https://user-images.githubusercontent.com/23090085/29396217-178406da-8349-11e7-9c0b-635113bcc09d.jpg)

確實實現了VerticalStepperItemView
![04](https://user-images.githubusercontent.com/23090085/29396222-216d2e88-8349-11e7-9096-372a9a2a0ad5.jpg)

但是出現了一個新的問題
![05](https://user-images.githubusercontent.com/23090085/29396229-2b46ba96-8349-11e7-9e54-f2b870e52c23.jpg)

於是我試著添加recyclerview的依賴
![06](https://user-images.githubusercontent.com/23090085/29396251-49180bb0-8349-11e7-80b8-7018afef48c0.jpg)

可是仍然有問題
![07](https://user-images.githubusercontent.com/23090085/29396261-61d7944a-8349-11e7-838f-10a7b8194f42.jpg)

我應該怎麼做 才能解決這個問題? 謝謝

**Comment by fython** [comment]
RecyclerView 從 26.0.0 版本開始不再通過 Android SDK 管理獲取，需要在你的項目根目錄的 `build.gradle` 中加入 Google 的 Maven Repo，例如：
```gradle
allprojects {
    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
        maven { url "https://jitpack.io" }
    }
}
```

_PS: MaterialStepperView 庫裏面依賴 RecyclerView 寫了一個 VerticalStepperView，所以會用到它。我在考慮要不要將它分離出來，有時候大家可能認為直接使用 ItemView 就足夠了。_

**Comment by fython** [comment]
@tenSunFree 如果沒有其它相關問題，當前這個問題也解決了的話，可以先關閉掉這個 Issue。
